### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by iBasit** [arabeyes-org/ITL-ports#2]
I have installed ITL  https://github.com/arabeyes-org/ITL  and even did `make install`

After installing that, I'm installing this library on mac and I keep getting following error.

Command (I'm not sure what path is for ITL, so I have tried many, even the parent folder path itl, but nothing works):

```
./configure --with-itl=/Applications/MAMP/bin/php/php5.6.10/include/itl/build/libitl.a 
```

Error:

```
checking for itl support... yes, shared
checking for itl files in default path... not found
configure: error: Please reinstall the itl distribution
```

**Comment by linostar** [comment]
First make sure there is a file named "prayer.h" in /Applications/MAMP/bin/php/php5.6.10/include/itl
Open file "php/config.m4", go to line 9 and replace it by the following:
SEARCH_PATH="/usr/local /usr /Applications/MAMP/bin/php/php5.6.10"

**Comment by iBasit** [comment]
I have added the line in `php/config.m4`.

There was no `prayer.h`, but it was in prayertimes folder, so I copy and pasted in itl parent folder. but I'm still getting same error.

following is directory structure 
![image](https://cloud.githubusercontent.com/assets/34341/15130286/1f9fcfde-163f-11e6-88e4-dc215d2b2131.png)

**Comment by iBasit** [comment]
Thank you
